# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_to_rod1
      - rod1_to_rod2
      - rod2_to_rod3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - rod3_to_left_finger
      - rod3_to_right_finger
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity